# Generated by Django 5.2.1 on 2025-09-16 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_blogpost_options_blogpost_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='city',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='consent_to_data_processing',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='country',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='nationality',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='responsibilities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='salary_range',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('interview', 'Interview'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ApplicationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500)),
                ('question_type', models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Long Text'), ('email', 'Email'), ('phone', 'Phone'), ('select', 'Dropdown'), ('checkbox', 'Checkbox'), ('file', 'File Upload')], default='text', max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('options', models.TextField(blank=True, help_text='Comma-separated options for dropdown/checkbox questions')),
                ('order', models.IntegerField(default=0)),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.jobposting')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='main.jobapplication')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.applicationquestion')),
            ],
        ),
    ]
