# Generated by Django 5.2.1 on 2025-09-18 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_jobapplication_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
