# Generated by Django 5.2.1 on 2025-09-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_blogpost_options_alter_blogpost_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationquestion',
            name='job_posting',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='ApplicationAnswer',
        ),
        migrations.DeleteModel(
            name='ApplicationQuestion',
        ),
    ]
