# Generated by Django 5.2.1 on 2025-09-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_applicationquestion_job_posting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='nationality',
            field=models.CharField(default='Egyptian', max_length=100),
        ),
    ]
